# Generated by Django 2.1.3 on 2019-07-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=10)),
                ('passWord', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('emailCode', models.CharField(blank=True, max_length=10)),
                ('emailCodeTime', models.DateTimeField(blank=True)),
            ],
        ),
    ]
